/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.KhoaNganh;
import Model.Sinhvien;
import Service.KhoaNganhService;
import Service.SinhvienService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class ListSinhVien extends javax.swing.JFrame {
    SinhvienService svService = new SinhvienService();
    KhoaNganhService knService = new KhoaNganhService();
    List<Sinhvien> listSv = new ArrayList<>();
    List<KhoaNganh> listKn = new ArrayList<>();
    DefaultTableModel defaultTable = new DefaultTableModel();
    
    /**
     * Creates new form SinhVienForm
     */
    public ListSinhVien() {
        initComponents();
        listSv = svService.getListSinhVienDb();
        listKn = knService.getAllKhoaNganh();
        cboKhoaNganh.setModel(new DefaultComboBoxModel(listKn.toArray()));
        loadTable();
    }
    
    private void loadTable() {
        defaultTable = (DefaultTableModel) tblListSv.getModel();
        if (!listSv.isEmpty()) {
            defaultTable.setRowCount(0);
            for(Sinhvien sv: listSv) {
                defaultTable.addRow(new Object[] {
                    sv.getMaSv(), sv.getTenSv(), sv.getSdt(), sv.getEmail()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboKhoaNganh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListSv = new javax.swing.JTable();
        TTSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboKhoaNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaNganhActionPerformed(evt);
            }
        });

        tblListSv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma Sv", "Ho ten", "So dien thoai", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListSv);

        TTSV.setText("TTSV");
        TTSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(cboKhoaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(TTSV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKhoaNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaNganhActionPerformed
        // TODO add your handling code here:
        KhoaNganh kn = (KhoaNganh) cboKhoaNganh.getSelectedItem();
        listSv = svService.getListSinhVienByKnDb(kn.getMaKn());
        loadTable();
    }//GEN-LAST:event_cboKhoaNganhActionPerformed

    private void TTSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTSVActionPerformed
        // TODO add your handling code here:
        KhoaNganh kn = (KhoaNganh) cboKhoaNganh.getSelectedItem();
        Sinhvien sv = listSv.get(tblListSv.getSelectedRow());
        SinhVienForm svNew = new SinhVienForm(kn.getMaKn(), sv);
        svNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TTSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TTSV;
    private javax.swing.JComboBox<KhoaNganh> cboKhoaNganh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListSv;
    // End of variables declaration//GEN-END:variables
}
